### ISSUE TITLE
JSON output does not work when exception occurs

### ISSUE THREAD

**Issue by gwillem** [netz98/n98-magerun#768]
Hi & thanks for making magerun, it is fantastic! 

Current behaviour in case of exception (wrong db pass for example) is:
```
$ n98-magerun.phar sys:modules:list --no-ansi --format=json 2>/dev/null
                                                                                         
  [Zend_Db_Adapter_Exception]                                                            
  SQLSTATE[HY000] [1045] Access denied for user 'app'@'127.0.0.1' (using password: YES)  
                                                                                         
                                                                                         
  [PDOException]                                                                         
  SQLSTATE[HY000] [1045] Access denied for user 'app'@'127.0.0.1' (using password: YES)  
                                                                                         
```

IMHO, it should print the exceptions to STDERR and return no output or an empty JSON dict. The JSON format is really convenient for automating tasks, but JSON parsers will jam on this output.

**Comment by tkn98** [comment]
@gwillem: Thank you for your report.

Can you quickly check if the status is non-zero (signals failure) - just to not have two problems already here.

The exception handling is done in the third-party components we use, I have to take a look if putting them to stderr is supported.

Do you see the usage instructions for that command *after* the exceptions?

**Comment by gwillem** [comment]
Thanks for the quick reply. 

Exit code is indeed `1` and usage is after the exceptions (but perhaps my shell flushes stdout & stderr in the wrong order).

However, I noticed I get an InvalidArgumentException with might indicate another problem. When the DB credentials are working, I do not get this exception for the same command line arguments. My DB credentials are stored in `~/.my.cnf`. 

```
$ /tmp/n98-magerun.phar sys:modules:list --format=json 

  [Zend_Db_Adapter_Exception]                                                            
  SQLSTATE[HY000] [1045] Access denied for user 'app'@'127.0.0.1' (using password: YES)  

  [PDOException]                                                                         
  SQLSTATE[HY000] [1045] Access denied for user 'app'@'127.0.0.1' (using password: YES)  

  [InvalidArgumentException]       
  The helper "io" is not defined.  

dev:module:list [--codepool [CODEPOOL]] [--status [STATUS]] [--vendor [VENDOR]] [--format [FORMAT]]

$ echo $?
1
```

**Comment by tkn98** [comment]
This is an early exception when the Magento application is being initialized. That's the reason why there is this "io"-helper exception. This might constitute a problem on it's own.

Is it that "`dev:module:list [--codepool `..." is output to standard-error already? (is it removed when you redirect 2 to dev/null?)

This is some material to look into.

**Comment by gwillem** [comment]
The cli usage is indeed sent to STDERR already!

**Comment by ktomk** [comment]
@gwillem: I've pushed some changes to the development branch. You should be able to run a self-update against the development version (--unstable) to obtain it. The exceptions then should be send to stderr instead of stdout. Additionally the InvalidArgument Exception should be gone.

Please try and let me know if it solves your issue.

**Comment by pocallaghan** [comment]
I'm not sure how feasible it would be, but would it be helpful if JSON output could contain an "error" key that provided any errors encountered during the request? I'm just thinking of how API's such as twitter work, I realise this isn't exactly the same thing, just floating the idea out there.

**Comment by gwillem** [comment]
@ktomk I've upgraded per your instructions. Now there are no more exceptions on stdout (profit!). I still get an InvalidArgumentException though. 

```
$ /tmp/n98-magerun.phar --version
                                                                                        
  [Zend_Db_Adapter_Exception]                                                            
  SQLSTATE[HY000] [1045] Access denied for user 'app'@'127.0.0.1' (using password: YES)  
                                                                                                                                                                                
  [PDOException]                                                                         
  SQLSTATE[HY000] [1045] Access denied for user 'app'@'127.0.0.1' (using password: YES)  
                                                                                         
n98-magerun version 1.97.12 by netz98 new media GmbH

$ /tmp/n98-magerun.phar sys:modules:list --format=json 
                                                                                         
  [Zend_Db_Adapter_Exception]                                                            
  SQLSTATE[HY000] [1045] Access denied for user 'app'@'127.0.0.1' (using password: YES)  
                                                                                         
  [PDOException]                                                                         
  SQLSTATE[HY000] [1045] Access denied for user 'app'@'127.0.0.1' (using password: YES)  
                                                                                         

  [InvalidArgumentException]       
  The helper "io" is not defined.  
                                   
dev:module:list [--codepool [CODEPOOL]] [--status [STATUS]] [--vendor [VENDOR]] [--format [FORMAT]]
```

**Comment by tkn98** [comment]
@gwillem Is the InvalidArgumentException within stderr or stdout? And can you give me a quick hint how this could be reproduced (I guess configured but DB server down)?

@pocallaghan when those exceptions are thrown it's yet outside of the concrete command. So this is not that easy at first glance.

**Comment by gwillem** [comment]
@tkn98 InvalidArgumentException is on stderr, so that in itself is good!

Reproduce: add garbage to your my.cnf:
```
cat > ~/.my.cnf <<EOM
[client]
user = bla
password = bla
EOM
```

**Comment by pocallaghan** [comment]
@tkn98 I figured that would likely be the case to be honest, I just wanted to put the idea out there.

**Comment by gwillem** [comment]
Thanks again for your quick and adequate action!

**Comment by ktomk** [comment]
@gwillem: thank you for the report and the quick responses. I could tackle the other problem now as well, fixes are part of the development version will be available with the next stable release.
